<?php

namespace Database\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version00000000000044 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE company_rel_kuaizhen (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', client_id VARCHAR(255) NOT NULL COMMENT \'client_id 580提供\', client_secret VARCHAR(255) NOT NULL COMMENT \'client_secret 580提供\', online TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否上线:0:未开启，1:已开启\', is_open TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否开启:0:未开启，1:已开启\', kuaizhen_store_id BIGINT DEFAULT 0 NOT NULL COMMENT \'kuaizhen580门店ID\', created INT DEFAULT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商城关联580快诊配置\' ');
        $this->addSql('CREATE TABLE items_medicine (item_id BIGINT NOT NULL COMMENT \'商品id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', medicine_type SMALLINT NOT NULL COMMENT \'药品分类:0为西药，1为中成药，3为其他\', common_name VARCHAR(255) NOT NULL COMMENT \'通用名（重要，具体请查看《同步药品信息规范指引》文档）\', dosage VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'剂型\', spec VARCHAR(255) NOT NULL COMMENT \'规格（重要，具体请查看《同步药品信息规范指引》文档）\', packing_spec VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'包装规格\', manufacturer VARCHAR(255) NOT NULL COMMENT \'生产厂家\', approval_number VARCHAR(255) NOT NULL COMMENT \'批准文号\', unit VARCHAR(255) NOT NULL COMMENT \'最小售卖单位\', is_prescription SMALLINT NOT NULL COMMENT \'是否处方药（1为是，0为否）\', special_common_name VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'特殊通用名\', special_spec VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'特殊规格\', audit_status SMALLINT DEFAULT 1 NOT NULL COMMENT \'审核状态，0不需要审核（非处方药），1未审核，2审核通过，3审核不通过\', audit_reason VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'审核不通过原因\', item_type VARCHAR(255) DEFAULT \'normal\' NOT NULL COMMENT \'商品类型 normal普通商品 point积分商品\', use_tip VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'处方药用药提示\', symptom VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'处方药适用症状\', max_num INT DEFAULT 0 NOT NULL COMMENT \'处方药单次下单最大购买数量\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX ix_company_id (company_id), INDEX ix_medicine_type (medicine_type), INDEX ix_common_name (common_name), INDEX ix_approval_number (approval_number), INDEX ix_is_prescription (is_prescription), PRIMARY KEY(item_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商品药品数据表\' ');
        $this->addSql('CREATE TABLE medication_personnel (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', company_id BIGINT NOT NULL COMMENT \'公司id\', user_id BIGINT NOT NULL COMMENT \'用户id\', user_family_name VARCHAR(255) NOT NULL COMMENT \'用药人姓名\', user_family_id_card VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'用药人身份证号\', user_family_age INT NOT NULL COMMENT \'用药人年龄\', user_family_gender SMALLINT NOT NULL COMMENT \'用药人性别1-男，2-女\', user_family_phone VARCHAR(255) NOT NULL COMMENT \'用药人手机号码\', relationship SMALLINT NOT NULL COMMENT \'用药人与问诊人关系(1本人 2父母 3配偶 4子女 5其他)\', is_default SMALLINT DEFAULT 0 NOT NULL COMMENT \'是否默认\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_company_id (company_id), INDEX idx_user_id (user_id), INDEX idx_user_family_id_card (user_family_id_card), INDEX idx_is_default (is_default), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'用药人信息\' ');
        $this->addSql('CREATE TABLE orders_diagnosis (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'自增id\', order_id VARCHAR(64) NOT NULL COMMENT \'订单号\', user_id BIGINT DEFAULT NULL COMMENT \'用户id\', company_id BIGINT NOT NULL COMMENT \'公司id\', kuaizhen_store_id BIGINT NOT NULL COMMENT \'580门店Id\', distributor_id BIGINT NOT NULL COMMENT \'店铺id\', service_type SMALLINT NOT NULL COMMENT \'服务类型，0为图文，1为视频\', is_examine SMALLINT NOT NULL COMMENT \'是否需要审方（0为不需要，1为需要）\', is_pregnant_woman SMALLINT NOT NULL COMMENT \'用药人是否孕妇（0为否，1为是）\', is_lactation SMALLINT NOT NULL COMMENT \'用药人是否哺乳期0为否，1为是\', souce_from SMALLINT DEFAULT 0 NOT NULL COMMENT \'来源（0为微信小程序，1为APP，2为H5，3为支付宝小程序）\', user_family_name VARCHAR(255) NOT NULL COMMENT \'用药人姓名\', user_family_id_card VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'用药人身份证号\', user_family_age INT NOT NULL COMMENT \'用药人年龄\', user_family_gender SMALLINT NOT NULL COMMENT \'用药人性别1-男，2-女\', user_family_phone VARCHAR(255) NOT NULL COMMENT \'用药人手机号码\', relationship SMALLINT NOT NULL COMMENT \'用药人与问诊人关系(1本人 2父母 3配偶 4子女 5其他)\', before_ai_data_list LONGTEXT DEFAULT NULL COMMENT \'AI问诊前5道题\', prescription_status SMALLINT DEFAULT 1 NOT NULL COMMENT \'开方状态，1未开方，2已开方，3医生拒绝开方\', prescription_refuse_reason VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'拒绝开方原因\', location_url LONGTEXT NOT NULL COMMENT \'跳转问诊H5页面地址\', status SMALLINT DEFAULT 1 NOT NULL COMMENT \'问诊单状态（1为进行中，2为已完成,5-AI问诊时取消）\', end_time INT DEFAULT 0 NOT NULL COMMENT \'问诊结束时间\', cancel_time INT DEFAULT 0 NOT NULL COMMENT \'问诊取消时间\', doctor_office VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'医生科室\', doctor_name VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'医生姓名\', hospital_name VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'互联网医院名称\', first_visit_list LONGTEXT DEFAULT NULL COMMENT \'首诊信息\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_order_id (order_id), INDEX idx_company_id (company_id), INDEX idx_user_id (user_id), INDEX idx_distributor_id (distributor_id), INDEX idx_status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'问诊单\' ');
        $this->addSql('CREATE TABLE orders_prescription (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'自增id\', order_id VARCHAR(64) NOT NULL COMMENT \'订单号\', diagnosis_id BIGINT NOT NULL COMMENT \'问诊单id\', user_id BIGINT DEFAULT NULL COMMENT \'用户id\', company_id BIGINT NOT NULL COMMENT \'公司id\', distributor_id BIGINT NOT NULL COMMENT \'店铺id\', prescription_id BIGINT NOT NULL COMMENT \'快诊580处方ID\', hospital_name VARCHAR(255) NOT NULL COMMENT \'互联网医院名称\', kuaizhen_store_id BIGINT NOT NULL COMMENT \'580门店Id\', kuaizhen_store_name VARCHAR(255) NOT NULL COMMENT \'580门店名称\', kuaizhen_diagnosis_id BIGINT NOT NULL COMMENT \'580问诊单ID\', doctor_sign_time BIGINT NOT NULL COMMENT \'医生签署时间(时间戳)\', doctor_office VARCHAR(255) NOT NULL COMMENT \'医生科室\', doctor_id BIGINT NOT NULL COMMENT \'医生id\', doctor_name VARCHAR(255) NOT NULL COMMENT \'医生姓名\', user_family_name VARCHAR(255) NOT NULL COMMENT \'就诊人姓名\', user_family_phone VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'就诊人手机号码\', user_family_age INT NOT NULL COMMENT \'就诊人年龄\', user_family_gender SMALLINT NOT NULL COMMENT \'就诊人性别，0未知，1男，2女\', user_family_id_card VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'用药人身份证号\', tags VARCHAR(255) NOT NULL COMMENT \'诊断标签\', status SMALLINT NOT NULL COMMENT \'处方状态(1正常 2已作废)\', memo VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'备注\', remarks VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'补充说明\', reason VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'审核不通过的理由（可能为空）\', dst_file_path VARCHAR(255) NOT NULL COMMENT \'处方图片地址\', serial_no VARCHAR(255) NOT NULL COMMENT \'处方编号\', drug_rsp_list LONGTEXT DEFAULT NULL COMMENT \'药品信息说明\', audit_status SMALLINT DEFAULT 1 NOT NULL COMMENT \'处方审核状态，1未审核，2审核通过，3审核不通过，4不需要审方\', audit_time INT DEFAULT 0 NOT NULL COMMENT \'审方时间\', audit_reason VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'审方不通过原因\', audit_apothecary_name VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'审方药师名称\', is_deleted SMALLINT DEFAULT 0 NOT NULL COMMENT \'是否已废弃, 0否  1是\', delete_time INT DEFAULT 0 NOT NULL COMMENT \'废弃时间\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_order_id (order_id), INDEX idx_diagnosis_id (diagnosis_id), INDEX idx_company_id (company_id), INDEX idx_user_id (user_id), INDEX idx_distributor_id (distributor_id), INDEX idx_status (status), INDEX idx_is_deleted (is_deleted), INDEX idx_user_family_name (user_family_name), INDEX idx_user_family_phone (user_family_phone), INDEX idx_user_family_id_card (user_family_id_card), INDEX idx_doctor_name (doctor_name), INDEX idx_serial_no (serial_no), INDEX idx_audit_apothecary_name (audit_apothecary_name), INDEX idx_audit_status (audit_status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'问诊单开方数据\' ');
        $this->addSql('ALTER TABLE distribution_distributor ADD kuaizhen_store_id BIGINT DEFAULT 0 NOT NULL COMMENT \'kuaizhen580门店ID\'');
        $this->addSql('ALTER TABLE items ADD is_medicine SMALLINT DEFAULT 0 NOT NULL COMMENT \'是否为药品，0否 1是\', ADD is_prescription SMALLINT DEFAULT 0 NOT NULL COMMENT \'是否为处方药，0否 1是\'');
        $this->addSql('CREATE INDEX ix_is_medicine ON items (is_medicine)');
        $this->addSql('CREATE INDEX ix_is_prescription ON items (is_prescription)');
        $this->addSql('ALTER TABLE orders_normal_orders ADD prescription_status INT DEFAULT 0 NOT NULL COMMENT \'开方状态，0不需要开方，1未开方，2已开方，处方药开方后才能继续支付\'');
        $this->addSql('CREATE INDEX idx_prescription_status ON orders_normal_orders (prescription_status)');
        $this->addSql('ALTER TABLE orders_normal_orders_items ADD is_prescription INT DEFAULT 0 NOT NULL COMMENT \'是否为处方药商品,0否 1是\'');
        $this->addSql('ALTER TABLE pointsmall_items ADD is_medicine SMALLINT DEFAULT 0 NOT NULL COMMENT \'是否为药品，0否 1是\', ADD is_prescription SMALLINT DEFAULT 0 NOT NULL COMMENT \'是否为处方药，0否 1是\'');
        $this->addSql('ALTER TABLE supplier_items ADD is_medicine SMALLINT DEFAULT 0 NOT NULL COMMENT \'是否为药品，0否 1是\', ADD is_prescription SMALLINT DEFAULT 0 NOT NULL COMMENT \'是否为处方药，0否 1是\'');
        $this->addSql('CREATE INDEX ix_is_medicine ON supplier_items (is_medicine)');
        $this->addSql('CREATE INDEX ix_is_prescription ON supplier_items (is_prescription)');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
    }
}
