<?php

namespace Database\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version00000000000050 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE icbc_pay_log (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'企业ID\', order_id VARCHAR(64) DEFAULT NULL COMMENT \'订单号\', unique_key VARCHAR(64) DEFAULT \'\' COMMENT \'唯一ID\', log_type VARCHAR(20) DEFAULT NULL COMMENT \'日志类型\', log_data LONGTEXT DEFAULT NULL COMMENT \'日志内容\', api_res LONGTEXT DEFAULT NULL COMMENT \'请求结果\', add_time DATETIME DEFAULT NULL COMMENT \'创建时间\', modify_time DATETIME DEFAULT NULL COMMENT \'更新时间\', INDEX idx_company_id (company_id), INDEX idx_order_id (order_id), INDEX idx_unique_key (unique_key), INDEX idx_add_time (add_time), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'工商银行接口日志\' ');
        $this->addSql('CREATE TABLE lucky_draw_activity (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'抽奖id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', area_id BIGINT NOT NULL COMMENT \'区域id\', begin_time BIGINT NOT NULL COMMENT \'开始时间\', end_time BIGINT NOT NULL COMMENT \'结束时间\', cost_type BIGINT NOT NULL COMMENT \'消耗类型，1互动分2积分\', cost_value BIGINT NOT NULL COMMENT \'具体的消耗值\', limit_total BIGINT NOT NULL COMMENT \'活动期限内总限制\', limit_day BIGINT NOT NULL COMMENT \'按天限制\', activity_type VARCHAR(64) DEFAULT NULL COMMENT \'活动类型，wheel为大转盘\', activity_name VARCHAR(255) DEFAULT NULL COMMENT \'活动名称\', activity_template_config LONGTEXT DEFAULT NULL COMMENT \'活动模板配置\', prize_data LONGTEXT DEFAULT NULL COMMENT \'奖项配置\', intro LONGTEXT DEFAULT NULL COMMENT \'活动说明\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'抽奖表\' ');
        $this->addSql('CREATE TABLE orders_invoice (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'自增id\', invoice_apply_bn VARCHAR(64) NOT NULL COMMENT \'发票申请单号\', user_id BIGINT NOT NULL COMMENT \'用户id\', company_id BIGINT NOT NULL COMMENT \'公司id\', regionauth_id BIGINT DEFAULT NULL COMMENT \'区域id\', order_id VARCHAR(255) NOT NULL COMMENT \'订单id，多订单以英文逗号分隔\', invoice_type VARCHAR(20) NOT NULL COMMENT \'开票类型，企业enterprise,和个人individual\', company_title VARCHAR(255) NOT NULL COMMENT \'公司抬头\', company_tax_number VARCHAR(64) DEFAULT NULL COMMENT \'公司税号\', company_address VARCHAR(255) DEFAULT NULL COMMENT \'公司地址\', company_telephone VARCHAR(20) DEFAULT NULL COMMENT \'公司电话\', bank_name VARCHAR(255) DEFAULT NULL COMMENT \'开户银行\', bank_account VARCHAR(64) DEFAULT NULL COMMENT \'开户账号\', email VARCHAR(255) DEFAULT NULL COMMENT \'电子邮箱\', mobile VARCHAR(20) DEFAULT NULL COMMENT \'手机号码\', invoice_status VARCHAR(20) DEFAULT \'pending\' NOT NULL COMMENT \'开票状态：待开票：pending，开票中：inProgress，开票成功：success，已作废：waste，开票失败：failed\', invoice_amount INT DEFAULT 0 COMMENT \'开票金额，以分为单位\', invoice_file_url VARCHAR(255) DEFAULT NULL COMMENT \'发票文件地址\', invoice_method VARCHAR(20) DEFAULT \'online\' NOT NULL COMMENT \'开票类型：线上和线下\', invoice_source VARCHAR(20) NOT NULL COMMENT \'开票来源：user客户端,oms\', remark VARCHAR(255) DEFAULT NULL COMMENT \'备注\', is_oms INT DEFAULT 0 NOT NULL COMMENT \'是否推送OMS，0是未推送，1是已推送\', create_time INT NOT NULL COMMENT \'创建时间\', update_time INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_invoice_apply_bn (invoice_apply_bn), INDEX idx_company_id (company_id), INDEX idx_user_id (user_id), INDEX idx_order_id (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'订单发票表\' ');
        $this->addSql('CREATE TABLE orders_invoice_item (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'自增id\', user_id BIGINT NOT NULL COMMENT \'用户id\', company_id BIGINT NOT NULL COMMENT \'公司id\', invoice_id BIGINT NOT NULL COMMENT \'关联发票表id\', invoice_apply_bn VARCHAR(64) NOT NULL COMMENT \'发票申请单号\', order_id VARCHAR(64) NOT NULL COMMENT \'订单号\', oid VARCHAR(64) DEFAULT NULL COMMENT \'OMS系统订单ID\', item_name VARCHAR(255) NOT NULL COMMENT \'商品名称\', item_bn VARCHAR(64) DEFAULT NULL COMMENT \'商品编码\', main_img VARCHAR(255) DEFAULT NULL COMMENT \'商品主图\', spec_info VARCHAR(255) DEFAULT NULL COMMENT \'商品规格\', num INT NOT NULL COMMENT \'数量\', amount INT NOT NULL COMMENT \'金额，以分为单位\', create_time INT NOT NULL COMMENT \'创建时间\', update_time INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_invoice_id (invoice_id), INDEX idx_invoice_apply_bn (invoice_apply_bn), INDEX idx_company_id (company_id), INDEX idx_user_id (user_id), INDEX idx_order_id (order_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'订单发票商品表\' ');
        $this->addSql('CREATE TABLE orders_invoice_log (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'自增id\', invoice_id BIGINT NOT NULL COMMENT \'关联发票表id\', operator_type VARCHAR(20) NOT NULL COMMENT \'操作类型\', user_id BIGINT DEFAULT NULL COMMENT \'用户id\', operator_id BIGINT DEFAULT NULL COMMENT \'操作人id\', operator_content JSON DEFAULT NULL COMMENT \'操作内容(DC2Type:json_array)\', create_time INT NOT NULL COMMENT \'创建时间\', update_time INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_invoice_id (invoice_id), INDEX idx_user_id (user_id), INDEX idx_operator_id (operator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'订单发票日志表\' ');
        $this->addSql('CREATE TABLE orders_invoices (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'自增id\', invoice_id BIGINT NOT NULL COMMENT \'关联发票表id\', company_id BIGINT NOT NULL COMMENT \'公司id\', invoice_type VARCHAR(20) NOT NULL COMMENT \'开票类型，红red,和蓝blue\', invoice_no VARCHAR(255) DEFAULT NULL COMMENT \'发票号码\', invoice_code VARCHAR(255) DEFAULT NULL COMMENT \'发票代码\', invoice_time VARCHAR(255) DEFAULT NULL COMMENT \'开票时间\', create_time INT NOT NULL COMMENT \'创建时间\', update_time INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_invoice_id (invoice_id), INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'发票表\' ');
        $this->addSql('CREATE TABLE popularize_promoter_identity (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'企业ID\', name VARCHAR(255) DEFAULT NULL COMMENT \'推广员身份名称\', is_subordinates INT NOT NULL COMMENT \'是否可发展下级分销员\', is_default INT NOT NULL COMMENT \'是否为默认\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX idx_companyid (company_id), INDEX idx_is_subordinates (is_subordinates), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'推广员身份表\' ');
        $this->addSql('CREATE TABLE promotion_user_task (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司ID\', user_id BIGINT NOT NULL COMMENT \'会员id\', create_time INT NOT NULL COMMENT \'签到时间\', tag VARCHAR(255) DEFAULT NULL COMMENT \'标签\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'签到日志\' ');
        $this->addSql('CREATE TABLE user_signin (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'记录id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', user_id BIGINT NOT NULL COMMENT \'用户id\', sign_date DATE NOT NULL COMMENT \'签到日期\', created INT NOT NULL, updated INT DEFAULT NULL, INDEX ix_company_id (company_id), INDEX ix_user_id (user_id), INDEX ix_sign_date (sign_date), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'用户签到表\' ');
        $this->addSql('CREATE TABLE user_signin_logs (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'记录id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', user_id BIGINT NOT NULL COMMENT \'用户id\', type INT NOT NULL COMMENT \'1日常签到，2，规则打标，3活动规则达标\', reward_title VARCHAR(255) NOT NULL COMMENT \'获奖标题\', activity_id BIGINT NOT NULL COMMENT \'活动id\', reward_text LONGTEXT NOT NULL COMMENT \'奖项记录多条\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'用户签到奖励记录表\' ');
        $this->addSql('CREATE TABLE user_signin_rules (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'记录id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', rule_name VARCHAR(255) NOT NULL COMMENT \'规则名称\', type BIGINT NOT NULL COMMENT \'1连续2累计\', days_required  BIGINT NOT NULL COMMENT \'需要的天数\', reward_text LONGTEXT NOT NULL COMMENT \'奖励类型 points积分，coupon券，coupons券包\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'用户签到规则表\' ');
        $this->addSql('CREATE TABLE user_task_activity (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司ID\', area_id BIGINT DEFAULT 0 NOT NULL COMMENT \'区域id\', title VARCHAR(255) NOT NULL COMMENT \'活动标题\', begin_time BIGINT DEFAULT 0 NOT NULL COMMENT \'开始时间\', end_time BIGINT DEFAULT 0 NOT NULL COMMENT \'结束时间\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'签到日志\' ');
        $this->addSql('CREATE TABLE user_task_activity_rule (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司ID\', activity_id BIGINT DEFAULT 0 NOT NULL COMMENT \'活动id\', rule_type VARCHAR(255) NOT NULL COMMENT \'活动类型\', rule_detail_type VARCHAR(255) NOT NULL COMMENT \'活动详细类型，理解为二级类型\', rule_name VARCHAR(255) NOT NULL COMMENT \'规则名称\', sign_type BIGINT NOT NULL COMMENT \'1连续2累计\', rule_desc VARCHAR(255) NOT NULL COMMENT \'规则名称\', hidde_tag VARCHAR(255) NOT NULL COMMENT \'用户标签\', finish_tag VARCHAR(255) NOT NULL COMMENT \'完成标签\', binding_distributors VARCHAR(255) NOT NULL COMMENT \'指定店铺\', binding_category VARCHAR(255) NOT NULL COMMENT \'指定管理分类\', share_pic VARCHAR(255) NOT NULL COMMENT \'分享图\', qr_code VARCHAR(255) NOT NULL COMMENT \'企微二维码\', frequency BIGINT NOT NULL COMMENT \'频次，1每天2每周3每月0为活动周期内\', common_condition VARCHAR(255) NOT NULL COMMENT \'常规的门槛，比如限制金额，限制页面，等等\', prize_text LONGTEXT NOT NULL COMMENT \'奖励信息\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'签到活动规则\' ');
        $this->addSql('CREATE TABLE user_task_finish_rule (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司ID\', activity_id BIGINT DEFAULT 0 NOT NULL COMMENT \'活动id\', user_id BIGINT DEFAULT 0 NOT NULL COMMENT \'用户id\', rule_id VARCHAR(255) NOT NULL COMMENT \'规则\', finish_status INT NOT NULL COMMENT \'1完成，2未完成\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'活动规则完成任务\' ');
        $this->addSql('DROP TABLE promotions_seckill_rel_category');
        $this->addSql('ALTER TABLE aftersales_detail ADD goods_id BIGINT NOT NULL COMMENT \'产品id\'');
        $this->addSql('ALTER TABLE items ADD start_num INT DEFAULT 0 COMMENT \'起订量\'');
        $this->addSql('ALTER TABLE items_attributes ADD attribute_show VARCHAR(15) DEFAULT NULL COMMENT \'属性展示方式 select 下拉 input 平铺\'');
        $this->addSql('ALTER TABLE kaquan_user_discount ADD activity_name VARCHAR(100) DEFAULT NULL COMMENT \'参与活动名称\', CHANGE card_id card_id BIGINT NOT NULL COMMENT \'微信用户领取的卡券 id \'');
        $this->addSql('ALTER TABLE members_info ADD name VARCHAR(255) DEFAULT NULL COMMENT \'名称\'');
        $this->addSql('ALTER TABLE orders_delivery_items ADD goods_id BIGINT NOT NULL COMMENT \'产品id\'');
        $this->addSql('ALTER TABLE orders_normal_orders ADD invoice_status VARCHAR(255) DEFAULT \'PENDING\' NOT NULL COMMENT \'开票状态。可选值有 DONE—已开票;PENDING—待开票;PARTAIL-部分开票\'');
        $this->addSql('ALTER TABLE orders_normal_orders_items ADD is_invoice INT DEFAULT 0 NOT NULL COMMENT \'是否开票,0否 1是\'');
        $this->addSql('ALTER TABLE popularize_promoter ADD identity_id BIGINT DEFAULT 0 NOT NULL COMMENT \'推广员身份ID\', ADD is_subordinates INT DEFAULT 0 NOT NULL COMMENT \'是否可发展下级分销员\', ADD pname VARCHAR(255) DEFAULT NULL COMMENT \'上级推广员名称\', ADD promoter_name VARCHAR(255) DEFAULT NULL COMMENT \'推广员名称\', ADD regions_id LONGTEXT DEFAULT NULL COMMENT \'地区ID\', ADD address VARCHAR(255) DEFAULT NULL COMMENT \'地址\'');
        $this->addSql('CREATE INDEX idx_identity_id ON popularize_promoter (identity_id)');
        $this->addSql('CREATE INDEX idx_is_subordinates ON popularize_promoter (is_subordinates)');
        $this->addSql('ALTER TABLE promotions_seckill_activity DROP tag_ids, DROP brand_ids, CHANGE use_bound use_bound INT DEFAULT 1 NOT NULL COMMENT \'适用范围: 1:指定商品可用\'');
        $this->addSql('ALTER TABLE promotions_turntable_log ADD act_id BIGINT NOT NULL COMMENT \'抽奖活动的活动id\'');
        $this->addSql('ALTER TABLE statement_details ADD num INT DEFAULT NULL COMMENT \'购买数量\', ADD item_fee INT DEFAULT NULL COMMENT \'销售总金额，以分为单位\', ADD commission_fee INT DEFAULT NULL COMMENT \'佣金金额，以分为单位\', ADD cost_fee INT DEFAULT NULL COMMENT \'结算金额，以分为单位\', ADD point_fee INT DEFAULT NULL COMMENT \'积分抵扣 按分计算\', ADD refund_num INT DEFAULT NULL COMMENT \'退货数量\', ADD refund_point INT DEFAULT NULL COMMENT \'退款积分\', ADD refund_cost_fee INT DEFAULT NULL COMMENT \'退货成本\'');
        $this->addSql('ALTER TABLE statements ADD point_fee INT DEFAULT NULL COMMENT \'积分抵扣 按分计算\', ADD refund_num INT DEFAULT NULL COMMENT \'退货数量\', ADD refund_point INT DEFAULT NULL COMMENT \'退款积分\', ADD refund_cost_fee INT DEFAULT NULL COMMENT \'退货成本\'');
        $this->addSql('ALTER TABLE supplier_items ADD start_num INT DEFAULT 0 COMMENT \'起订量\'');
    	$this->addSql('CREATE TABLE thirdparty_dmcrm_log (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', company_id BIGINT NOT NULL COMMENT \'公司id\', api_type VARCHAR(255) NOT NULL COMMENT \'日志同步类型, response:响应，request:请求\', worker VARCHAR(255) NOT NULL COMMENT \'api\', params JSON DEFAULT NULL COMMENT \'任务参数(DC2Type:json_array)\', result JSON DEFAULT NULL COMMENT \'返回数据(DC2Type:json_array)\', status VARCHAR(255) DEFAULT \'running\' NOT NULL COMMENT \'运行状态：running,success,fail\', runtime VARCHAR(255) DEFAULT NULL COMMENT \'运行时间(秒)\', created INT NOT NULL, updated INT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'达摩crm通信日志\' ');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('DROP TABLE thirdparty_dmcrm_log');
    }
}
