<?php

namespace Database\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema as Schema;

class Version00000000000039 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE bspay_div_fee (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', trade_id VARCHAR(64) NOT NULL COMMENT \'交易单号\', order_id VARCHAR(64) DEFAULT NULL COMMENT \'订单号\', company_id VARCHAR(255) NOT NULL COMMENT \'企业ID\', distributor_id VARCHAR(255) DEFAULT NULL COMMENT \'店铺ID\', operator_type VARCHAR(255) NOT NULL COMMENT \'操作者类型:distributor-店铺;dealer-经销;admin:超级管理员\', pay_fee INT UNSIGNED DEFAULT 0 NOT NULL COMMENT \'支付金额\', div_fee INT UNSIGNED DEFAULT 0 COMMENT \'当前用户的分账金额，以分为单位\', huifu_id VARCHAR(255) DEFAULT \'\' COMMENT \'汇付ID\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX ix_company_id (company_id), INDEX ix_distributor_id (distributor_id), INDEX ix_order_id (order_id), INDEX ix_trade_id (trade_id), INDEX ix_list (company_id, huifu_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'分账金额表\' ');
        $this->addSql('CREATE TABLE bspay_entry_apply (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', user_name VARCHAR(64) NOT NULL COMMENT \'用户名\', company_id BIGINT DEFAULT NULL COMMENT \'公司id\', user_id VARCHAR(255) NOT NULL COMMENT \'开户进件ID\', operator_id INT DEFAULT 0 COMMENT \'操作者id\', operator_type VARCHAR(255) NOT NULL COMMENT \'操作者类型:distributor-店铺;dealer-经销;promoter-推广员\', user_type VARCHAR(20) DEFAULT \'indv\' NOT NULL COMMENT \'进件类型\', address VARCHAR(255) DEFAULT NULL COMMENT \'所属地区\', comments LONGTEXT DEFAULT NULL COMMENT \'审批意见\', status VARCHAR(20) DEFAULT NULL COMMENT \'WAIT_APPROVE;APPROVED;REJECT\', created INT NOT NULL, updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX ix_company_id (company_id), INDEX ix_user_id (user_id), INDEX ix_operator_type (operator_type), INDEX ix_status (status), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'开户申请表\' ');
        $this->addSql('CREATE TABLE bspay_paymemt_confirm (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', order_id VARCHAR(255) NOT NULL COMMENT \'订单id\', distributor_id BIGINT DEFAULT NULL COMMENT \'店铺id\', payment_id VARCHAR(255) DEFAULT NULL COMMENT \'斗拱生成的交易订单号 对应order表的transaction_id\', payment_confirmation_id VARCHAR(255) DEFAULT NULL COMMENT \'支付确认id\', order_no VARCHAR(255) DEFAULT NULL COMMENT \'支付确认请求订单号\', confirm_amt VARCHAR(255) DEFAULT NULL COMMENT \'确认金额 单位：元\', div_members LONGTEXT DEFAULT NULL COMMENT \'分账对象信息列表 json\', status VARCHAR(255) DEFAULT NULL COMMENT \'交易状态\', request_params LONGTEXT DEFAULT NULL COMMENT \'请求参数 json\', response_params LONGTEXT DEFAULT NULL COMMENT \'响应参数 json\', created INT NOT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_company_id (company_id), INDEX idx_order_id (order_id), INDEX idx_order_no (order_no), INDEX distributor_id (distributor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'斗拱支付确认表\' ');
        $this->addSql('CREATE TABLE bspay_regions_third (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', area_name VARCHAR(50) NOT NULL COMMENT \'名称\', pid BIGINT NOT NULL COMMENT \'父级ID\', area_code VARCHAR(50) NOT NULL COMMENT \'编码\', INDEX idx_area_name (area_name), INDEX idx_area_code (area_code), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'省市区编码(六位码或九位码)\' ');
        $this->addSql('CREATE TABLE bspay_user_card (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', sys_id VARCHAR(255) DEFAULT \'\' COMMENT \'商户的huifu_id\', huifu_id VARCHAR(255) DEFAULT \'\' COMMENT \'汇付ID\', user_id BIGINT NOT NULL COMMENT \'开户进件ID\', req_seq_id VARCHAR(64) DEFAULT \'\' COMMENT \'请求流水号\', company_id BIGINT DEFAULT NULL COMMENT \'公司id\', user_type VARCHAR(20) DEFAULT \'indv\' NOT NULL COMMENT \'进件类型\', card_type VARCHAR(10) DEFAULT \'0\' NOT NULL COMMENT \'结算银行卡账户类型 0：对公，1：对私，2：对私非法人；\', card_name VARCHAR(500) DEFAULT \'\' NOT NULL COMMENT \'结算银行卡持卡人姓名\', card_no VARCHAR(100) DEFAULT \'\' NOT NULL COMMENT \'结算银行卡卡号\', prov_id VARCHAR(12) DEFAULT \'\' NOT NULL COMMENT \'结算卡银行所在省\', area_id VARCHAR(12) DEFAULT \'\' NOT NULL COMMENT \'结算卡银行所在市\', bank_code VARCHAR(12) DEFAULT \'\' COMMENT \'结算卡银行号，对公必填\', branch_name VARCHAR(100) DEFAULT \'\' COMMENT \'结算卡支行名称，对公时必填\', cert_no VARCHAR(32) DEFAULT \'\' COMMENT \'结算卡持卡人身份证号，对私必填\', cert_validity_type INT DEFAULT 0 COMMENT \'结算卡持卡人身份证有效期类型 1:长期有效 0:非长期有效；\', cert_begin_date VARCHAR(8) DEFAULT \'\' NOT NULL COMMENT \'结算卡持卡人证件有效期（起始） 日期格式：yyyyMMdd\', cert_end_date VARCHAR(8) DEFAULT \'\' COMMENT \'结算卡持卡人证件有效期（截止） 日期格式：yyyyMMdd;非长期有效时必填\', mp VARCHAR(255) DEFAULT \'\' COMMENT \'结算银行卡绑定手机号\', apply_no VARCHAR(30) DEFAULT \'\' COMMENT \'申请单号\', audit_state VARCHAR(50) DEFAULT \'\' COMMENT \'审核状态，状态包括：A-审核中；B-配置成功；C-配置失败\', audit_desc VARCHAR(200) DEFAULT \'\' COMMENT \'审核结果描述\', error_info VARCHAR(500) DEFAULT \'\' COMMENT \'错误描述\', created INT NOT NULL, updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_user_id (user_id), INDEX idx_card_no (card_no(64)), INDEX idx_company_id (company_id), INDEX idx_huifu_id (huifu_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'用户结算账户\' ');
        $this->addSql('CREATE TABLE bspay_user_ent (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', req_seq_id VARCHAR(64) DEFAULT \'\' COMMENT \'请求流水号\', sys_id VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'商户的huifu_id\', huifu_id VARCHAR(255) DEFAULT \'\' COMMENT \'汇付ID\', company_id BIGINT DEFAULT NULL COMMENT \'公司id\', is_update INT DEFAULT 0 NOT NULL COMMENT \'是否审核成功后修改 1:是  0:否\', reg_name VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'企业名称\', license_code VARCHAR(32) DEFAULT \'\' NOT NULL COMMENT \'营业执照编号\', license_validity_type INT DEFAULT 0 COMMENT \'营业执照有效期类型 1:长期有效 0:非长期有效；\', license_begin_date VARCHAR(8) DEFAULT \'\' NOT NULL COMMENT \'营业执照有效期起始日期 日期格式：yyyyMMdd\', license_end_date VARCHAR(8) DEFAULT \'\' COMMENT \'营业执照有效期结束日期 日期格式：yyyyMMdd;非长期有效时必填\', reg_prov_id VARCHAR(12) DEFAULT \'\' COMMENT \'注册地址(省)\', reg_area_id VARCHAR(12) DEFAULT \'\' NOT NULL COMMENT \'注册地址(市)\', reg_district_id VARCHAR(12) DEFAULT \'\' NOT NULL COMMENT \'注册地址(区)\', reg_detail VARCHAR(300) DEFAULT \'\' NOT NULL COMMENT \'注册地址(详细信息)\', legal_name VARCHAR(500) DEFAULT \'\' NOT NULL COMMENT \'法人姓名\', legal_cert_no VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'法人身份证号码\', legal_cert_validity_type INT DEFAULT 0 COMMENT \'法人身份证有效期类型 1:长期有效 0:非长期有效；\', legal_cert_begin_date VARCHAR(8) DEFAULT \'\' NOT NULL COMMENT \'法人身份证有效期开始日期\', legal_cert_end_date VARCHAR(8) DEFAULT \'\' COMMENT \'法人身份证有效期截止日期 日期格式：yyyyMMdd;非长期有效时必填\', contact_name VARCHAR(500) DEFAULT \'\' NOT NULL COMMENT \'联系人姓名\', contact_mobile VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'联系人手机\', ent_type INT DEFAULT 1 NOT NULL COMMENT \'公司类型 1:政府机构 2:国营企业 3:私营企业 4:外资企业 5:个体工商户 6:其它组织 7:事业单位 8:集体经济\', audit_state VARCHAR(50) DEFAULT \'\' COMMENT \'审核状态，状态包括：A-待审核；B-审核失败；C-开户失败；D-开户成功但未创建结算账户；E-开户和创建结算账户成功\', audit_desc VARCHAR(200) DEFAULT \'\' COMMENT \'审核结果描述\', error_info VARCHAR(500) DEFAULT \'\' COMMENT \'错误描述\', created INT NOT NULL, updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_req_seq_id (req_seq_id), INDEX idx_company_id (company_id), INDEX idx_sys_id (sys_id), INDEX idx_huifu_id (huifu_id), INDEX idx_audit_state (audit_state), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'企业用户对象\' ');
        $this->addSql('CREATE TABLE bspay_user_indv (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', req_seq_id VARCHAR(64) DEFAULT \'\' COMMENT \'请求流水号\', sys_id VARCHAR(255) DEFAULT \'\' COMMENT \'商户的huifu_id\', huifu_id VARCHAR(255) DEFAULT \'\' COMMENT \'汇付ID\', company_id BIGINT DEFAULT NULL COMMENT \'公司id\', is_update INT DEFAULT 0 NOT NULL COMMENT \'是否审核成功后修改 1:是  0:否\', name VARCHAR(500) DEFAULT \'\' NOT NULL COMMENT \'个人姓名\', cert_no VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'个人身份证号码\', cert_validity_type INT DEFAULT 0 COMMENT \'个人身份证有效期类型 1:长期有效 0:非长期有效；\', cert_begin_date VARCHAR(8) DEFAULT \'\' NOT NULL COMMENT \'个人身份证有效期开始日期\', cert_end_date VARCHAR(8) DEFAULT \'\' COMMENT \'个人身份证有效期截止日期 日期格式：yyyyMMdd;非长期有效时必填\', mobile_no VARCHAR(255) DEFAULT \'\' NOT NULL COMMENT \'手机号\', audit_state VARCHAR(50) DEFAULT \'A\' COMMENT \'审核状态，状态包括：A-待审核；B-审核失败；C-开户失败；D-开户成功但未创建结算账户；E-开户和创建结算账户成功\', audit_desc VARCHAR(500) DEFAULT \'\' COMMENT \'审核结果描述\', error_info VARCHAR(500) DEFAULT \'\' COMMENT \'错误描述\', created INT NOT NULL, updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_company_id (company_id), INDEX idx_sys_id (sys_id), INDEX idx_huifu_id (huifu_id), INDEX idx_audit_state (audit_state), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'个人用户\' ');
        $this->addSql('CREATE TABLE bspay_user_update_log (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT DEFAULT NULL COMMENT \'公司id\', sys_id VARCHAR(100) DEFAULT \'\' NOT NULL COMMENT \'sys_id\', huifu_id VARCHAR(255) DEFAULT \'\' COMMENT \'汇付ID\', user_type VARCHAR(20) DEFAULT \'indv\' NOT NULL COMMENT \'进件类型\', user_id VARCHAR(255) NOT NULL COMMENT \'用户表的主键id\', data LONGTEXT NOT NULL COMMENT \'修改数据 json\', audit_state VARCHAR(50) DEFAULT \'A\' COMMENT \'审核状态，状态包括：A-待审核；B-审核失败；C-开户失败；D-开户成功但未创建结算账户；E-开户和创建结算账户成功\', audit_desc VARCHAR(500) DEFAULT \'\' COMMENT \'审核结果描述\', created INT NOT NULL, updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_company_id (company_id), INDEX idx_sys_id (sys_id), INDEX idx_user_id (user_id), INDEX idx_huifu_id (huifu_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'用户进件修改log(审核成功后修改)\' ');
        $this->addSql('CREATE TABLE business_rep_user (relation_id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'关系ID（自增主键）\', business_rep_id VARCHAR(255) NOT NULL COMMENT \'业务员ID（外键，关联到业务员表）\', user_id BIGINT NOT NULL COMMENT \'用户id\', assigned_date DATE NOT NULL COMMENT \'指定日期（即业务员开始服务该用户的日期）\', description LONGTEXT DEFAULT NULL COMMENT \'关系描述（可选，用于记录特殊说明）\', create_time bigint NOT NULL, INDEX idx_user_id (user_id), UNIQUE INDEX user_bussiness_id (user_id, business_rep_id), PRIMARY KEY(relation_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'业务员关联会员\' ');
        $this->addSql('CREATE TABLE business_representative (business_rep_id BIGINT AUTO_INCREMENT NOT NULL, user_id BIGINT NOT NULL, name VARCHAR(100) NOT NULL, gender VARCHAR(6) DEFAULT NULL, age INT DEFAULT NULL, hire_date DATE NOT NULL, department_id INT DEFAULT NULL, job_title VARCHAR(50) NOT NULL, sales_performance NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, customer_relations_score NUMERIC(5, 2) DEFAULT \'0.00\' NOT NULL, is_active TINYINT(1) DEFAULT \'1\' NOT NULL, create_time INT NOT NULL, INDEX idx_user_id (user_id), UNIQUE INDEX user_bussiness_id (user_id, business_rep_id), PRIMARY KEY(business_rep_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'业务员\' ');
        $this->addSql('CREATE TABLE company_rel_shansong (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL COMMENT \'公司id\', shop_id VARCHAR(255) NOT NULL COMMENT \'商户ID\', client_id VARCHAR(255) NOT NULL COMMENT \'App-key\', app_secret VARCHAR(255) NOT NULL COMMENT \'App-密钥\', online TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否上线:0:未开启，1:已开启\', freight_type TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'运费承担方:0:商家承担，1:买家承担\', is_open TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否开启:0:未开启，1:已开启\', created INT DEFAULT NULL COMMENT \'创建时间\', updated INT DEFAULT NULL COMMENT \'更新时间\', INDEX idx_company_id (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商城关联闪送应用配置信息表\' ');
        $this->addSql('CREATE TABLE items_commission (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'id\', company_id BIGINT NOT NULL COMMENT \'公司ID\', rel_id BIGINT NOT NULL COMMENT \'关联ID\', type VARCHAR(255) DEFAULT \'goods\' COMMENT \'数据类型 goods:SPU,item:SKU\', commission_type VARCHAR(255) DEFAULT \'1\' COMMENT \'佣金计算方式 1:按照比例,2:按照填写金额\', commission_conf JSON DEFAULT NULL COMMENT \'佣金(DC2Type:json_array)\', INDEX ix_company_id (company_id), INDEX ix_rel_id (rel_id), INDEX ix_type (type), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'商品佣金配置表\' ');
        $this->addSql('CREATE TABLE self_delivery_staff (id BIGINT AUTO_INCREMENT NOT NULL COMMENT \'ID\', company_id BIGINT NOT NULL, operator_id BIGINT NOT NULL, distributor_id INT DEFAULT 0 COMMENT \'配送员所属店铺id\', shop_id INT DEFAULT 0 COMMENT \'配送员所属门店id\', staff_attribute VARCHAR(255) DEFAULT \'full_time\' NOT NULL COMMENT \'配送员属性。full_time:全职;part_time:兼职;\', staff_no VARCHAR(255) DEFAULT NULL COMMENT \'配送员编号。\', staff_type VARCHAR(255) DEFAULT \'distributor\' NOT NULL COMMENT \'配送员类型。platform:平台;distributor:店铺;shop:商家;\', payment_method VARCHAR(255) DEFAULT \'order\' NOT NULL COMMENT \'结算方式。order:订单;amount:订单金额;\', payment_fee INT DEFAULT 0 NOT NULL COMMENT \'结合payment_method计算使用，结算费用 分 或 百分比\', created bigint NOT NULL, updated bigint NOT NULL, INDEX idx_company_id (company_id), INDEX idx_operator_id (operator_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'自配送员工信息表\' ');
        $this->addSql('ALTER TABLE aftersales ADD self_delivery_operator_id BIGINT DEFAULT 0 COMMENT \'自配送员id\'');
        $this->addSql('ALTER TABLE distribution_distributor ADD house_number VARCHAR(255) DEFAULT NULL COMMENT \'详细地址，门牌号\', ADD is_self_delivery TINYINT(1) DEFAULT \'0\' COMMENT \'是否支持自配送\', ADD is_open_salesman TINYINT(1) DEFAULT \'0\' COMMENT \'是否开启业务员\', ADD bspay_split_ledger_info VARCHAR(255) DEFAULT NULL COMMENT \'斗拱分账信息\', ADD shansong_shop_create TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'该门店在闪送是否已创建,0:未创建,1:已创建\', ADD shansong_store_id BIGINT DEFAULT NULL COMMENT \'闪送店铺ID\', ADD freight_time INT DEFAULT 2 COMMENT \'自配送预计需要的时间（小时）\', CHANGE is_dada is_dada TINYINT(1) DEFAULT \'0\' NOT NULL COMMENT \'是否开启同城配（不仅限于达达）,0:未开启,1:已开启\'');
        $this->addSql('ALTER TABLE espier_uploadefile ADD merchant_id BIGINT DEFAULT 0 NOT NULL COMMENT \'商户id\'');
        $this->addSql('ALTER TABLE operators CHANGE operator_type operator_type VARCHAR(255) DEFAULT \'admin\' NOT NULL COMMENT \'操作员类型类型。admin:超级管理员;staff:员工;distributor:店铺管理员;dealer:经销商;merchant:商户;supplier:供应商;self_delivery_staff:自配送员\'');
        $this->addSql('ALTER TABLE orders_cart ADD promoter_user_id BIGINT DEFAULT NULL COMMENT \'推广员user_id\', CHANGE source_type source_type VARCHAR(255) DEFAULT \'normal\' NOT NULL COMMENT \'购物车数据来源：scancode：扫码加入购物车, normal:正常加入购物车,salesperson:业务员导购下单\'');
        $this->addSql('CREATE INDEX idx_promoter_user_id ON orders_cart (promoter_user_id)');
        $this->addSql('ALTER TABLE orders_delivery ADD self_delivery_operator_id BIGINT DEFAULT 0 COMMENT \'自配送员id\', ADD delivery_remark VARCHAR(255) DEFAULT NULL COMMENT \'配送备注\', ADD delivery_pics JSON DEFAULT NULL COMMENT \'配送图片(DC2Type:json_array)\'');
        $this->addSql('ALTER TABLE orders_normal_orders ADD self_delivery_status VARCHAR(255) DEFAULT \'NOTMERCHANT\' COMMENT \'店铺自配送状态。可选值有 CONFIRMING:等待确认;RECEIVEORDER:已接单;PACKAGED:已打包;DELIVERING:配送中;DONE:已送达;NOTMERCHANT:不是自配送;\', ADD order_holder VARCHAR(20) DEFAULT \'self\' COMMENT \'订单归属。可选值 self-自营订单;distributor-商家订单;supplier-供应商订单;self_supplier-自营和供应商订单\', ADD self_delivery_operator_id BIGINT DEFAULT 0 COMMENT \'自配送员id\', ADD self_delivery_fee INT DEFAULT 0 COMMENT \'操作者id\', ADD self_delivery_time INT DEFAULT 0 COMMENT \'自配送预约时间\', ADD self_delivery_end_time BIGINT DEFAULT NULL COMMENT \'自配送送达时间\', CHANGE order_source order_source VARCHAR(255) DEFAULT \'member\' COMMENT \'订单来源。可选值有 member-用户自主下单;shop-商家代客下单 salesperson:业务员导购下单\'');
        $this->addSql('CREATE INDEX idx_order_holder ON orders_normal_orders (order_holder)');
        $this->addSql('ALTER TABLE orders_process_log ADD is_show TINYINT(1) DEFAULT \'0\' COMMENT \'C端是否可见\', ADD pics JSON DEFAULT NULL COMMENT \'图片记录(DC2Type:json_array)\', ADD delivery_remark VARCHAR(255) DEFAULT NULL COMMENT \'订单发货备注\'');
        $this->addSql('ALTER TABLE trade ADD bspay_req_date VARCHAR(255) DEFAULT NULL COMMENT \'斗拱支付的请求日期\', ADD bspay_div_members VARCHAR(500) DEFAULT \'\' COMMENT \'斗拱分账对象信息列表，最多仅支持7个分账方，json 数组形式\', ADD bspay_div_status VARCHAR(255) DEFAULT NULL COMMENT \'斗拱分账状态。可选值有NOTDIV—未分账;DIVED-已分账;\', ADD bspay_fee_mode VARCHAR(255) DEFAULT \'\' COMMENT \'斗拱手续费收取模式 1:外扣 2:内扣\', ADD bspay_fee INT UNSIGNED DEFAULT 0 COMMENT \'斗拱分账手续费，以分为单位\'');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema): void
    {
    }
}
